create_password_reset_request:
    path:     /login/create_password_reset_request
    defaults: { _controller: inem0o\UserPasswordLostBundle\Controller\CreatePasswordResetRequestController:indexAction }

confirm_password_reset_request:
    path:     /login/confirm_password_reset_request
    defaults: { _controller: inem0o\UserPasswordLostBundle\Controller\CreatePasswordResetRequestController:confirmAction }

handle_password_reset_request:
    path:     /login/handle_password_reset_request/{token}
    defaults: { _controller: inem0o\UserPasswordLostBundle\Controller\HandlePasswordResetRequestController:indexAction }
    requirements:
      token: '[a-z0-9]+'
