<?php

namespace inem0o\UserPasswordLostBundle\Repository;

/**
 * PasswordResetRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetRequestIdentityRepository extends \Doctrine\ORM\EntityRepository
{
}
